# Generated by Django 4.2.1 on 2023-06-28 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_posts', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subscribe',
            field=models.ManyToManyField(blank=True, related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
